// Code generated by protoc-gen-go.
// source: gbfs/gbfs.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	gbfs/gbfs.proto

It has these top-level messages:
	AutoDiscoveryMessage
	StationStatusMessage
	StationInformationMessage
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/duration"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type AutoDiscoveryMessage struct {
	// Integer POSIX timestamp indicating the last time the data in this feed was updated
	LastUpdated int64 `protobuf:"varint,1,opt,name=last_updated" json:"last_updated,omitempty"`
	// Timestamp indicating the last time the data in this feed was updated
	LastUpdatedTimestamp *google_protobuf1.Timestamp `protobuf:"bytes,2,opt,name=last_updated_timestamp" json:"last_updated_timestamp,omitempty"`
	// Integer representing the number of seconds before the data in this feed will be updated again (0 if the data should always be refreshed)
	Ttl int64 `protobuf:"varint,3,opt,name=ttl" json:"ttl,omitempty"`
	// Number of seconds before the data in this feed will be updated again (0 if the data should always be refreshed)
	TtlDuration *google_protobuf.Duration `protobuf:"bytes,4,opt,name=ttl_duration" json:"ttl_duration,omitempty"`
	// Languages supported by feeds
	Data map[string]*AutoDiscoveryMessage_LanguageData `protobuf:"bytes,5,rep,name=data" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *AutoDiscoveryMessage) Reset()                    { *m = AutoDiscoveryMessage{} }
func (m *AutoDiscoveryMessage) String() string            { return proto1.CompactTextString(m) }
func (*AutoDiscoveryMessage) ProtoMessage()               {}
func (*AutoDiscoveryMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AutoDiscoveryMessage) GetLastUpdatedTimestamp() *google_protobuf1.Timestamp {
	if m != nil {
		return m.LastUpdatedTimestamp
	}
	return nil
}

func (m *AutoDiscoveryMessage) GetTtlDuration() *google_protobuf.Duration {
	if m != nil {
		return m.TtlDuration
	}
	return nil
}

func (m *AutoDiscoveryMessage) GetData() map[string]*AutoDiscoveryMessage_LanguageData {
	if m != nil {
		return m.Data
	}
	return nil
}

type AutoDiscoveryMessage_LanguageData struct {
	Feeds []*AutoDiscoveryMessage_Feed `protobuf:"bytes,1,rep,name=feeds" json:"feeds,omitempty"`
}

func (m *AutoDiscoveryMessage_LanguageData) Reset()         { *m = AutoDiscoveryMessage_LanguageData{} }
func (m *AutoDiscoveryMessage_LanguageData) String() string { return proto1.CompactTextString(m) }
func (*AutoDiscoveryMessage_LanguageData) ProtoMessage()    {}
func (*AutoDiscoveryMessage_LanguageData) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 1}
}

func (m *AutoDiscoveryMessage_LanguageData) GetFeeds() []*AutoDiscoveryMessage_Feed {
	if m != nil {
		return m.Feeds
	}
	return nil
}

type AutoDiscoveryMessage_Feed struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Url  string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
}

func (m *AutoDiscoveryMessage_Feed) Reset()                    { *m = AutoDiscoveryMessage_Feed{} }
func (m *AutoDiscoveryMessage_Feed) String() string            { return proto1.CompactTextString(m) }
func (*AutoDiscoveryMessage_Feed) ProtoMessage()               {}
func (*AutoDiscoveryMessage_Feed) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 2} }

type StationStatusMessage struct {
	// Integer POSIX timestamp indicating the last time the data in this feed was updated
	LastUpdated int64 `protobuf:"varint,1,opt,name=last_updated" json:"last_updated,omitempty"`
	// Timestamp indicating the last time the data in this feed was updated
	LastUpdatedTimestamp *google_protobuf1.Timestamp `protobuf:"bytes,2,opt,name=last_updated_timestamp" json:"last_updated_timestamp,omitempty"`
	// Integer representing the number of seconds before the data in this feed will be updated again (0 if the data should always be refreshed)
	Ttl int64 `protobuf:"varint,3,opt,name=ttl" json:"ttl,omitempty"`
	// Number of seconds before the data in this feed will be updated again (0 if the data should always be refreshed)
	TtlDuration *google_protobuf.Duration `protobuf:"bytes,4,opt,name=ttl_duration" json:"ttl_duration,omitempty"`
	// Stations
	Data *StationStatusMessage_Stations `protobuf:"bytes,5,opt,name=data" json:"data,omitempty"`
}

func (m *StationStatusMessage) Reset()                    { *m = StationStatusMessage{} }
func (m *StationStatusMessage) String() string            { return proto1.CompactTextString(m) }
func (*StationStatusMessage) ProtoMessage()               {}
func (*StationStatusMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StationStatusMessage) GetLastUpdatedTimestamp() *google_protobuf1.Timestamp {
	if m != nil {
		return m.LastUpdatedTimestamp
	}
	return nil
}

func (m *StationStatusMessage) GetTtlDuration() *google_protobuf.Duration {
	if m != nil {
		return m.TtlDuration
	}
	return nil
}

func (m *StationStatusMessage) GetData() *StationStatusMessage_Stations {
	if m != nil {
		return m.Data
	}
	return nil
}

type StationStatusMessage_Stations struct {
	Stations []*StationStatusMessage_Station `protobuf:"bytes,1,rep,name=stations" json:"stations,omitempty"`
}

func (m *StationStatusMessage_Stations) Reset()         { *m = StationStatusMessage_Stations{} }
func (m *StationStatusMessage_Stations) String() string { return proto1.CompactTextString(m) }
func (*StationStatusMessage_Stations) ProtoMessage()    {}
func (*StationStatusMessage_Stations) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

func (m *StationStatusMessage_Stations) GetStations() []*StationStatusMessage_Station {
	if m != nil {
		return m.Stations
	}
	return nil
}

type StationStatusMessage_Station struct {
	StationId             string                      `protobuf:"bytes,1,opt,name=station_id" json:"station_id,omitempty"`
	NumBikesAvailable     int64                       `protobuf:"varint,2,opt,name=num_bikes_available" json:"num_bikes_available,omitempty"`
	NumBikesDisabled      int64                       `protobuf:"varint,3,opt,name=num_bikes_disabled" json:"num_bikes_disabled,omitempty"`
	NumDocksAvailable     int64                       `protobuf:"varint,4,opt,name=num_docks_available" json:"num_docks_available,omitempty"`
	NumDocksDisabled      int64                       `protobuf:"varint,5,opt,name=num_docks_disabled" json:"num_docks_disabled,omitempty"`
	IsInstalled           int64                       `protobuf:"varint,6,opt,name=is_installed" json:"is_installed,omitempty"`
	IsRenting             int64                       `protobuf:"varint,7,opt,name=is_renting" json:"is_renting,omitempty"`
	IsReturning           int64                       `protobuf:"varint,8,opt,name=is_returning" json:"is_returning,omitempty"`
	LastReported          int64                       `protobuf:"varint,9,opt,name=last_reported" json:"last_reported,omitempty"`
	LastReportedTimestamp *google_protobuf1.Timestamp `protobuf:"bytes,10,opt,name=last_reported_timestamp" json:"last_reported_timestamp,omitempty"`
}

func (m *StationStatusMessage_Station) Reset()                    { *m = StationStatusMessage_Station{} }
func (m *StationStatusMessage_Station) String() string            { return proto1.CompactTextString(m) }
func (*StationStatusMessage_Station) ProtoMessage()               {}
func (*StationStatusMessage_Station) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 1} }

func (m *StationStatusMessage_Station) GetLastReportedTimestamp() *google_protobuf1.Timestamp {
	if m != nil {
		return m.LastReportedTimestamp
	}
	return nil
}

type StationInformationMessage struct {
	// Integer POSIX timestamp indicating the last time the data in this feed was updated
	LastUpdated int64 `protobuf:"varint,1,opt,name=last_updated" json:"last_updated,omitempty"`
	// Timestamp indicating the last time the data in this feed was updated
	LastUpdatedTimestamp *google_protobuf1.Timestamp `protobuf:"bytes,2,opt,name=last_updated_timestamp" json:"last_updated_timestamp,omitempty"`
	// Integer representing the number of seconds before the data in this feed will be updated again (0 if the data should always be refreshed)
	Ttl int64 `protobuf:"varint,3,opt,name=ttl" json:"ttl,omitempty"`
	// Number of seconds before the data in this feed will be updated again (0 if the data should always be refreshed)
	TtlDuration *google_protobuf.Duration `protobuf:"bytes,4,opt,name=ttl_duration" json:"ttl_duration,omitempty"`
	// Stations
	Data *StationInformationMessage_Stations `protobuf:"bytes,5,opt,name=data" json:"data,omitempty"`
}

func (m *StationInformationMessage) Reset()                    { *m = StationInformationMessage{} }
func (m *StationInformationMessage) String() string            { return proto1.CompactTextString(m) }
func (*StationInformationMessage) ProtoMessage()               {}
func (*StationInformationMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *StationInformationMessage) GetLastUpdatedTimestamp() *google_protobuf1.Timestamp {
	if m != nil {
		return m.LastUpdatedTimestamp
	}
	return nil
}

func (m *StationInformationMessage) GetTtlDuration() *google_protobuf.Duration {
	if m != nil {
		return m.TtlDuration
	}
	return nil
}

func (m *StationInformationMessage) GetData() *StationInformationMessage_Stations {
	if m != nil {
		return m.Data
	}
	return nil
}

type StationInformationMessage_Stations struct {
	Stations []*StationInformationMessage_Station `protobuf:"bytes,1,rep,name=stations" json:"stations,omitempty"`
}

func (m *StationInformationMessage_Stations) Reset()         { *m = StationInformationMessage_Stations{} }
func (m *StationInformationMessage_Stations) String() string { return proto1.CompactTextString(m) }
func (*StationInformationMessage_Stations) ProtoMessage()    {}
func (*StationInformationMessage_Stations) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 0}
}

func (m *StationInformationMessage_Stations) GetStations() []*StationInformationMessage_Station {
	if m != nil {
		return m.Stations
	}
	return nil
}

type StationInformationMessage_Station struct {
	StationId     string   `protobuf:"bytes,1,opt,name=station_id" json:"station_id,omitempty"`
	Name          string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	ShortName     string   `protobuf:"bytes,3,opt,name=short_name" json:"short_name,omitempty"`
	Lat           float64  `protobuf:"fixed64,4,opt,name=lat" json:"lat,omitempty"`
	Lon           float64  `protobuf:"fixed64,5,opt,name=lon" json:"lon,omitempty"`
	RegionId      int64    `protobuf:"varint,6,opt,name=region_id" json:"region_id,omitempty"`
	RentalMethods []string `protobuf:"bytes,7,rep,name=rental_methods" json:"rental_methods,omitempty"`
	Capacity      int64    `protobuf:"varint,8,opt,name=capacity" json:"capacity,omitempty"`
	RentalUrl     string   `protobuf:"bytes,9,opt,name=rental_url" json:"rental_url,omitempty"`
}

func (m *StationInformationMessage_Station) Reset()         { *m = StationInformationMessage_Station{} }
func (m *StationInformationMessage_Station) String() string { return proto1.CompactTextString(m) }
func (*StationInformationMessage_Station) ProtoMessage()    {}
func (*StationInformationMessage_Station) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 1}
}

func init() {
	proto1.RegisterType((*AutoDiscoveryMessage)(nil), "skidder.gbfs.AutoDiscoveryMessage")
	proto1.RegisterType((*AutoDiscoveryMessage_LanguageData)(nil), "skidder.gbfs.AutoDiscoveryMessage.LanguageData")
	proto1.RegisterType((*AutoDiscoveryMessage_Feed)(nil), "skidder.gbfs.AutoDiscoveryMessage.Feed")
	proto1.RegisterType((*StationStatusMessage)(nil), "skidder.gbfs.StationStatusMessage")
	proto1.RegisterType((*StationStatusMessage_Stations)(nil), "skidder.gbfs.StationStatusMessage.Stations")
	proto1.RegisterType((*StationStatusMessage_Station)(nil), "skidder.gbfs.StationStatusMessage.Station")
	proto1.RegisterType((*StationInformationMessage)(nil), "skidder.gbfs.StationInformationMessage")
	proto1.RegisterType((*StationInformationMessage_Stations)(nil), "skidder.gbfs.StationInformationMessage.Stations")
	proto1.RegisterType((*StationInformationMessage_Station)(nil), "skidder.gbfs.StationInformationMessage.Station")
}

func init() { proto1.RegisterFile("gbfs/gbfs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 708 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xdc, 0x56, 0x5b, 0x6f, 0xd3, 0x3e,
	0x14, 0x57, 0x9b, 0x76, 0x6b, 0xce, 0xfa, 0xbf, 0xc8, 0x4c, 0x90, 0x45, 0x30, 0xaa, 0x8a, 0x4b,
	0x05, 0x23, 0x9d, 0xc6, 0x0b, 0x42, 0x9a, 0xb8, 0xa8, 0x9b, 0x84, 0x60, 0x2f, 0x61, 0x12, 0x12,
	0x2f, 0x91, 0xdb, 0xb8, 0xa9, 0xd5, 0x24, 0xae, 0x6c, 0x67, 0x52, 0x9f, 0x79, 0x81, 0x6f, 0xc6,
	0x2b, 0xdf, 0x08, 0xd9, 0x71, 0xd2, 0xa4, 0xeb, 0x44, 0x79, 0xdd, 0x4b, 0x73, 0xfc, 0x3b, 0xf7,
	0xe3, 0xdf, 0xb1, 0x0a, 0xff, 0x45, 0xe3, 0xa9, 0x18, 0xaa, 0x1f, 0x6f, 0xc1, 0x99, 0x64, 0xa8,
	0x2b, 0xe6, 0x34, 0x0c, 0x09, 0xf7, 0x14, 0xe6, 0x1e, 0x46, 0x8c, 0x45, 0x31, 0x19, 0x6a, 0xdd,
	0x38, 0x9b, 0x0e, 0xc3, 0x8c, 0x63, 0x49, 0x59, 0x9a, 0x5b, 0xbb, 0x0f, 0xd7, 0xf5, 0x92, 0x26,
	0x44, 0x48, 0x9c, 0x2c, 0x72, 0x83, 0xfe, 0xf7, 0x16, 0xec, 0xbf, 0xcb, 0x24, 0x1b, 0x51, 0x31,
	0x61, 0x57, 0x84, 0x2f, 0x2f, 0x88, 0x10, 0x38, 0x22, 0xa8, 0x0f, 0xdd, 0x18, 0x0b, 0x19, 0x64,
	0x8b, 0x10, 0x4b, 0x12, 0x3a, 0x8d, 0x5e, 0x63, 0x60, 0xf9, 0x35, 0x0c, 0xf9, 0x70, 0xb7, 0x7a,
	0x0e, 0xca, 0xe0, 0x4e, 0xb3, 0xd7, 0x18, 0xec, 0x9d, 0xb8, 0x5e, 0x9e, 0xde, 0x2b, 0xd2, 0x7b,
	0x97, 0x85, 0x85, 0x7f, 0x83, 0x27, 0xfa, 0x1f, 0x2c, 0x29, 0x63, 0xc7, 0xd2, 0xe9, 0x94, 0x88,
	0x4e, 0xa1, 0x2b, 0x65, 0x1c, 0x14, 0x9d, 0x39, 0x2d, 0x1d, 0xfb, 0xe0, 0x5a, 0xec, 0x91, 0x31,
	0xf0, 0x6b, 0xe6, 0xe8, 0x2d, 0xb4, 0x42, 0x2c, 0xb1, 0xd3, 0xee, 0x59, 0x83, 0xbd, 0x93, 0x23,
	0xaf, 0x3a, 0x3f, 0x6f, 0x53, 0xeb, 0xde, 0x08, 0x4b, 0x7c, 0x96, 0x4a, 0xbe, 0xf4, 0xb5, 0xa7,
	0x3b, 0x03, 0xbb, 0x84, 0x54, 0x7d, 0x73, 0xb2, 0xd4, 0xe3, 0xb0, 0x7d, 0x25, 0xa2, 0x33, 0x68,
	0x5f, 0xe1, 0x38, 0x23, 0xa6, 0xe9, 0xe1, 0x16, 0x19, 0x3e, 0xe1, 0x34, 0xca, 0x70, 0x44, 0x54,
	0x58, 0x3f, 0xf7, 0x7e, 0xdd, 0x7c, 0xd5, 0x70, 0x2f, 0xa0, 0x5b, 0x55, 0xa1, 0x53, 0x68, 0x4f,
	0x09, 0x09, 0x85, 0xd3, 0xd0, 0xc5, 0x3f, 0xdd, 0x22, 0xf4, 0x39, 0x21, 0xa1, 0x9f, 0x7b, 0xb9,
	0x47, 0xd0, 0x52, 0x47, 0x84, 0xa0, 0x95, 0xe2, 0x84, 0x98, 0xa2, 0xb5, 0xac, 0xfa, 0xc8, 0x78,
	0xac, 0x6b, 0xb6, 0x7d, 0x25, 0xf6, 0x7f, 0xee, 0xc0, 0xfe, 0x67, 0xa9, 0x87, 0xa6, 0x3e, 0x99,
	0xb8, 0x75, 0x54, 0x78, 0x53, 0x52, 0x41, 0xb9, 0x3d, 0xaf, 0x4f, 0x73, 0x53, 0xeb, 0x05, 0x28,
	0x0c, 0x13, 0x7c, 0xe8, 0x14, 0x08, 0x3a, 0x87, 0x8e, 0x30, 0xb2, 0xb9, 0x9e, 0x67, 0xdb, 0x07,
	0xf4, 0x4b, 0x5f, 0xf7, 0x97, 0x05, 0xbb, 0x06, 0x45, 0x87, 0x00, 0x06, 0x0f, 0x68, 0x68, 0xae,
	0xab, 0x82, 0xa0, 0x63, 0xb8, 0x93, 0x66, 0x49, 0x30, 0xa6, 0x73, 0x22, 0x02, 0x7c, 0x85, 0x69,
	0x8c, 0xc7, 0x71, 0x4e, 0x3c, 0xcb, 0xdf, 0xa4, 0x42, 0x1e, 0xa0, 0x15, 0x1c, 0x52, 0xa1, 0xc0,
	0xd0, 0x8c, 0x74, 0x83, 0xa6, 0xc8, 0x10, 0xb2, 0xc9, 0xbc, 0x9a, 0xa1, 0xb5, 0xca, 0xb0, 0xa6,
	0x2a, 0x32, 0xe4, 0x70, 0x99, 0xa1, 0xbd, 0xca, 0x50, 0xd7, 0x28, 0x36, 0x51, 0x11, 0xd0, 0x54,
	0x48, 0x1c, 0x2b, 0xcb, 0x9d, 0x9c, 0x4d, 0x55, 0x4c, 0xcd, 0x81, 0x8a, 0x80, 0x93, 0x54, 0xd2,
	0x34, 0x72, 0x76, 0xb5, 0x45, 0x05, 0x31, 0x31, 0x38, 0x91, 0x19, 0x4f, 0x95, 0x45, 0xa7, 0x8c,
	0x51, 0x62, 0xe8, 0x11, 0xfc, 0xa3, 0x79, 0xc5, 0xc9, 0x82, 0x71, 0x45, 0x5b, 0x5b, 0x1b, 0xd5,
	0x41, 0x74, 0x09, 0xf7, 0x6a, 0x40, 0x85, 0xb8, 0xf0, 0x47, 0xe2, 0xde, 0xe4, 0xda, 0xff, 0xd1,
	0x86, 0x03, 0x73, 0xa7, 0x1f, 0xd2, 0x29, 0xe3, 0x89, 0x16, 0x6f, 0xdd, 0x3e, 0x8d, 0x6a, 0xfb,
	0x74, 0xbc, 0x91, 0xfe, 0xd7, 0xfb, 0x5f, 0x5f, 0xaa, 0x2f, 0x95, 0xa5, 0xfa, 0x78, 0x6d, 0xa9,
	0x86, 0x7f, 0x19, 0xb5, 0xb2, 0x59, 0xdf, 0x9a, 0xdb, 0x6f, 0x56, 0xf1, 0x44, 0x36, 0x2b, 0x4f,
	0xa4, 0xf2, 0x99, 0x31, 0x2e, 0x03, 0xad, 0xb1, 0x8c, 0x4f, 0x89, 0xa8, 0x79, 0xc6, 0x58, 0xea,
	0xa1, 0x35, 0x7c, 0x25, 0x6a, 0x84, 0xa5, 0x7a, 0x1e, 0x0a, 0x61, 0x29, 0xba, 0x0f, 0x36, 0x27,
	0x91, 0x49, 0x9b, 0x53, 0x7d, 0x05, 0xa0, 0x27, 0xf0, 0xaf, 0xa2, 0x34, 0x8e, 0x83, 0x84, 0xc8,
	0x19, 0x0b, 0x85, 0xb3, 0xdb, 0xb3, 0x06, 0xb6, 0xbf, 0x86, 0x22, 0x17, 0x3a, 0x13, 0xbc, 0xc0,
	0x13, 0x2a, 0x97, 0x86, 0xeb, 0xe5, 0x59, 0x55, 0x69, 0xac, 0xd5, 0x7b, 0x6e, 0xe7, 0x55, 0xae,
	0x90, 0xf7, 0xe7, 0xf0, 0x60, 0xc2, 0x12, 0x2f, 0xa2, 0x72, 0x96, 0x8d, 0xeb, 0xc3, 0xd4, 0xf7,
	0xfb, 0xf5, 0xb1, 0x51, 0x4d, 0x58, 0x32, 0x34, 0x6a, 0xfd, 0x87, 0xe3, 0x45, 0xc4, 0xf4, 0xd7,
	0xfc, 0x79, 0xd8, 0xd1, 0x9f, 0x97, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x8b, 0x09, 0xfe,
	0x92, 0x08, 0x00, 0x00,
}
